name: Check PR for CHANGELOG.md and package.json updates

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if changelog was changed
        id: changelog-changed
        uses: tj-actions/changed-files@v35
        with:
          files: CHANGELOG.md

      - name: Check for CHANGELOG.md updates
        if: steps.changelog-changed.outputs.any_changed != 'true'
        run: |
          echo "ERROR: CHANGELOG.md not updated"
          exit 1
